// src/lib/components/Project.svelte
<script lang="ts">
    import { capitalize } from "$lib/utils/capitalize";
    import DiGithubBadge from "svelte-icons/di/DiGithubBadge.svelte";
    // import Tag from "./Tag.svelte";

    export let name: string;
    export let description: string;
    export let url: string;
</script>

<article class="shadow border dark:border-gray-800 rounded-md px-4 py-2 flex flex-col justify-center">
    <header class="flex justify-between">
        <h2 class="text-2xl font-bold">{capitalize(name)}</h2>

        <div class="w-10 h-10">
            <a href={url} class="hover:text-brand" target="_blank">
                <DiGithubBadge />
            </a>
        </div>
    </header>

    <p>{description}</p>

    <!-- {#each tags as tag}
        <Tag color="blue">
            {tag}</Tag
        >
    {/each} -->
</article>

// src/components/Project.tsx
import Image from "next/image";
import { FaExternalLinkAlt, FaGithub } from "react-icons/fa";
import { IProject } from "../../data/projects";
import Tag from "./Tag";

interface Props {
    project: IProject;
}

export default function Project({ project }: Props) {
    return (
        <article
            key={project.name}
            className="rounded-md w-full dark:bg-gray-900 border dark:border-gray-800 break-inside shadow-sm"
        >
            {project.image && (
                <div className="aspect-w-16 aspect-h-9">
                    <Image
                        className="object-cover rounded-t-md"
                        src={project.image.url}
                        layout="fill"
                        alt={project.name}
                    />
                </div>
            )}
            <div className="p-4 flex flex-row space-x-6">
                <div className="flex-grow space-y-2">
                    <div className="flex flex-row justify-between">
                        <h1 className="text-2xl font-semibold tracking-tight">{project.name}</h1>
                        <div className="flex h-auto items-start space-x-4">
                            <a
                                href={project.github}
                                target="_blank"
                                className="hover:text-orange-300 tansform transition-transform hover:scale-105"
                                rel="noreferrer"
                            >
                                <FaGithub size={23} />
                            </a>
                            {project?.url && (
                                <a
                                    href={project?.url}
                                    target="_blank"
                                    className="hover:text-orange-300 tansform transition-transform hover:scale-105"
                                    rel="noreferrer"
                                >
                                    <FaExternalLinkAlt size={20} />
                                </a>
                            )}
                        </div>
                    </div>
                    <div className="flex flex-wrap">
                        {project.tags.map((tag, index) => (
                            <Tag tag={tag} key={`tag-${index}`} />
                        ))}
                    </div>
                    <p>{project.description}</p>
                </div>
            </div>
        </article>
    );
}
